--Excluir Tabelas
DROP TABLE IF EXISTS Categorias CASCADE;
DROP TABLE IF EXISTS Subcategorias CASCADE;
DROP TABLE IF EXISTS Produtos CASCADE;
DROP TABLE IF EXISTS Clientes CASCADE;
DROP TABLE IF EXISTS Pedidos CASCADE;
DROP TABLE IF EXISTS ItensPedidos CASCADE;
DROP TABLE IF EXISTS Pagamentos CASCADE;
DROP TABLE IF EXISTS Entregas CASCADE;
DROP TABLE IF EXISTS Funcionarios CASCADE;
DROP TABLE IF EXISTS Fornecedores CASCADE;
DROP TABLE IF EXISTS Estoque CASCADE;
DROP TABLE IF EXISTS Marcas CASCADE;